server:
  port: 80

spring:
  # freemarker 配置
  freemarker:
    template-loader-path: classpath:/templates/
    cache: false
    charset: utf-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: request
    suffix: .ftl
    settings:
      number_format: 0
      auto_import: /spring.ftl as spring
      classic_compatible: true
  # mysql 数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sale_demo?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: ccxx545400
    driverClassName: com.mysql.jdbc.Driver
  mvc:
    static-path-pattern: /static/**

mybatis:
  mapper-locations: classpath:mapper/*.xml

#pagehelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql